2015/12/03 23:00:04 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:00:04 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:00:59 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:00:59 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:01:00 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:01:00 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:01:00 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:01:00 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:01:00 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:01:00 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:01:01 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:01:01 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:01:01 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:01:01 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:01:01 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:01:02 [error] 866#0: *1 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:01:02 [error] 866#0: *10 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:01:02 [error] 866#0: *10 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:01:02 [error] 866#0: *10 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:01:02 [error] 866#0: *10 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:01:02 [error] 866#0: *10 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:01:02 [error] 866#0: *10 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:06:42 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:06:42 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:06:44 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:06:44 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:14 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:14 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:14 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:14 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:15 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:15 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:15 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:15 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:15 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:15 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:16 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:16 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:16 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:16 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:16 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:16 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:16 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:16 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:17 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:17 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:17 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:17 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:17 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:17 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:18 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:18 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:18 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:18 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:07:29 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:07:29 [crit] 866#0: *26 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:08:38 [crit] 866#0: *67 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:08:38 [crit] 866#0: *67 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:08:38 [crit] 866#0: *67 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:08:38 [crit] 866#0: *67 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:08:38 [crit] 866#0: *67 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:08:39 [crit] 866#0: *67 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:08:46 [crit] 866#0: *67 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:08:46 [crit] 866#0: *67 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (13: Permission denied) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:14:08 [error] 866#0: *78 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:14:08 [error] 866#0: *78 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:14:11 [error] 866#0: *78 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:14:11 [error] 866#0: *78 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:14:13 [error] 866#0: *78 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:14:13 [error] 866#0: *78 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
2015/12/03 23:15:51 [error] 866#0: *87 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000"
2015/12/03 23:15:51 [error] 866#0: *87 connect() to unix:///Users/kklt/Python/new/project/new.sock failed (61: Connection refused) while connecting to upstream, client: 10.183.39.11, server: 10.183.39.11, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://unix:///Users/kklt/Python/new/project/new.sock:", host: "10.183.39.11:9000", referrer: "http://10.183.39.11:9000/"
